algoritmo "ParImparProcedimentos"

var
   N: Inteiro
   Procedimento  ParOuImpar (V: Inteiro)
   Inicio
   Se (V%2=0) então
   Escreva ("O número ", V, " é par.")
   Senão
   Escreva ("O número ", V, " é ímpar.")
   FimSe
   FimProcedimento
inicio
   Escreval ("PAR OU IMPAR BY PROCEDIMENTOS")
   Escreval ("----------------------------")
   Escreva ("Digite um número: ")
   Leia (N)
   ParOuImpar(N)
   Escreval ("----------------------------")


fimalgoritmo